version: '3.8'

services:
  # -----------------------------
  # DATABASES
  # -----------------------------
  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"
    volumes:
      - product_db_data:/var/lib/mysql

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"
    volumes:
      - order_db_data:/var/lib/mysql

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: payment_db
    ports:
      - "3309:3306"
    volumes:
      - payment_db_data:/var/lib/mysql

  # -----------------------------
  # REDIS
  # -----------------------------
  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  # -----------------------------
  # KAFKA BROKER 1
  # -----------------------------
  kafka-1:
    image: apache/kafka:3.7.0
    container_name: kafka-broker-1
    hostname: kafka-1

    ports:
      - "19092:19092"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:19092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:19092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"

    volumes:
      - kafka_1_data:/var/lib/kafka/data

  # -----------------------------
  # KAFKA BROKER 2
  # -----------------------------
  kafka-2:
    image: apache/kafka:3.7.0
    container_name: kafka-broker-2
    hostname: kafka-2

    depends_on:
      - kafka-1

    ports:
      - "19093:19093"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker

      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:19093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:19093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"

    volumes:
      - kafka_2_data:/var/lib/kafka/data

  # -----------------------------
  # KAFKA BROKER 3
  # -----------------------------
  kafka-3:
    image: apache/kafka:3.7.0
    container_name: kafka-broker-3
    hostname: kafka-3

    depends_on:
      - kafka-1

    ports:
      - "19094:19094"

    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker

      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:19094

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,EXTERNAL://localhost:19094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"

    volumes:
      - kafka_3_data:/var/lib/kafka/data

  # -----------------------------
  # KAFKA UI
  # -----------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui

    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

    ports:
      - "8001:8080"

    environment:
      DYNAMIC_CONFIG_ENABLED: "true"

      KAFKA_CLUSTERS_0_NAME: ecommerce-cluster

      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092

  # -----------------------------
  # ZIPKIN
  # -----------------------------
  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin-server

    ports:
      - "9411:9411"

volumes:
  product_db_data:
  order_db_data:
  payment_db_data:

  kafka_1_data:
  kafka_2_data:
  kafka_3_data: